# .github/workflows/deploy-scheduler.yml
name: Deploy Scheduler

on:
  workflow_dispatch:
    inputs:
      RG:
        description: 'Resource group'
        required: false
        default: 'cursus-test-rg'
      APP:
        description: 'App name'
        required: false
        default: 'cursus-test-app'
      COSMOS:
        description: 'Cosmos account name'
        required: true
      SCHED_FUNC:
        description: 'Scheduler function name'
        required: true
  workflow_call:
    inputs:
      RG:
        required: false
        default: 'cursus-test-rg'
      APP:
        required: false
        default: 'cursus-test-app'
      COSMOS:
        required: true
      SCHED_FUNC:
        required: true

permissions:
  id-token: write
  contents: read

env:
  RG:         ${{ inputs.RG }}
  APP:        ${{ inputs.APP }}
  COSMOS:     ${{ inputs.COSMOS }}
  SCHED_FUNC: ${{ inputs.SCHED_FUNC }}

jobs:
  deploy_scheduler:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: pip

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Vendor scheduler deps & package ZIP
        shell: bash
        run: |
          set -eo pipefail
          pushd src/scheduler_fapp

          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir -r requirements.txt \
                                   --target .python_packages/lib/site-packages

          zip -qr ../../sched.zip . .python_packages
          popd

      - name: ZIP-deploy scheduler Function-App
        shell: bash
        run: |
          set -eo pipefail
          for attempt in 1 2 3; do
            if az functionapp deployment source config-zip \
                  -g $RG -n $SCHED_FUNC --src sched.zip --timeout 240; then
                break
            fi
            sleep $((attempt*30))
          done

          status=$(az functionapp show -g $RG -n $SCHED_FUNC --query state -o tsv)
          [[ "$status" == "Running" ]] || exit 1

      - name: Verify scheduler health endpoint
        shell: bash
        run: |
          url="https://$SCHED_FUNC.azurewebsites.net/api/healthz"
          for i in {1..10}; do
            code=$(curl -s -o /dev/null -w '%{http_code}' "$url" || true)
            [[ "$code" == "200" ]] && exit 0
            sleep 15
          done
          exit 1

      - name: Grant Cosmos role (scheduler MSI)
        run: |
          principalId=$(az webapp identity show -g $RG -n $SCHED_FUNC --query principalId -o tsv)
          roleId=$(az cosmosdb sql role definition list -g $RG --account-name $COSMOS \
                   --query "[?roleName=='Cosmos DB Built-in Data Contributor'].id" -o tsv)
          az cosmosdb sql role assignment create -g $RG --account-name $COSMOS \
            --principal-id $principalId \
            --role-definition-id $roleId \
            --scope "/" || true

      - name: Update web-app with scheduler settings
        run: |
          sched_base="https://$SCHED_FUNC.azurewebsites.net"
          az webapp config appsettings set \
            -g $RG -n $APP --settings \
            SCHEDULER_BASE_URL=$sched_base \
            SCHEDULER_FUNCTION_NAME=$SCHED_FUNC \
            SCHEDULER_MGMT_KEY=""

      - name: Upload scheduler logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: scheduler-log
          path: sched.log
