# ── .github/workflows/orchestrator.yml ───────────────────────────────
name: Azure Deployment (Test) – Orchestrator

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  RG:          cursus-test-rg
  LOCATION:    eastasia
  APP:         cursus-test-app
  PLAN_SKU:    B1
  TIMEOUT:     1800

jobs:
  infra:
    uses: ./.github/workflows/infra.yml
    with:
      rg:         ${{ env.RG }}
      location:   ${{ env.LOCATION }}
      app:        ${{ env.APP }}
      plan_sku:   ${{ env.PLAN_SKU }}
      timeout:    ${{ env.TIMEOUT }}
    secrets: inherit

  webapp:
    needs: infra
    uses: ./.github/workflows/webapp.yml
    with:
      rg:        ${{ env.RG }}
      location:  ${{ env.LOCATION }}
      app:       ${{ env.APP }}
      cosmos:    ${{ jobs.infra.outputs.cosmos }}
      timeout:   ${{ env.TIMEOUT }}
    secrets: inherit

  scheduler:
    needs: webapp
    uses: ./.github/workflows/scheduler.yml
    with:
      rg:         ${{ env.RG }}
      app:        ${{ env.APP }}
      cosmos:     ${{ jobs.infra.outputs.cosmos }}
      sched_func: ${{ jobs.infra.outputs.sched_func }}
      timeout:    ${{ env.TIMEOUT }}
    secrets: inherit
