name: Deploy scheduler (Durable Function)

on:
  workflow_call:
    inputs:
      RG:
        description: Resource group name
        required: true
        type: string
      APP:
        description: Web-app name
        required: true
        type: string
      TIMEOUT:
        description: Deployment timeout
        required: true
        type: string
      COSMOS:
        description: Cosmos account name
        required: true
        type: string
      SCHED_FUNC:
        description: Scheduler Function name
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  deploy-scheduler:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: pip

      - uses: azure/login@v1
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Vendor scheduler deps and ZIP package
        shell: bash
        run: |
          set -eo pipefail
          pushd src/scheduler_fapp

          echo "📦 Installing Python deps into .python_packages/"
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir -r requirements.txt \
                                   --target .python_packages/lib/site-packages

          echo "🗜  Creating deployment ZIP"
          zip -qr ../../sched.zip . .python_packages
          popd
          echo "📦 scheduler zip size: $(du -h sched.zip | cut -f1)"

      - name: ZIP-deploy scheduler Function-App
        shell: bash
        run: |
          set -eo pipefail
          for attempt in 1 2 3; do
            echo "🚀 ZIP deploy attempt $attempt"
            if az functionapp deployment source config-zip \
                  -g ${{ inputs.RG }} -n ${{ inputs.SCHED_FUNC }} --src sched.zip --timeout 240; then
                echo "✅ scheduler zip deploy succeeded"
                break
            fi
            echo "⚠️ attempt $attempt failed – backing off $((attempt*30)) s"
            sleep $((attempt*30))
          done

          status=$(az functionapp show -g ${{ inputs.RG }} -n ${{ inputs.SCHED_FUNC }} --query state -o tsv)
          [[ "$status" == "Running" ]] || { echo "💥 scheduler failed to start"; exit 1; }

          echo "🚀 scheduler running – tailing log 60 s …"
          timeout 60s az webapp log tail -g ${{ inputs.RG }} -n ${{ inputs.SCHED_FUNC }} | tee sched.log || true

      - name: Verify scheduler health endpoint
        shell: bash
        run: |
          set -eo pipefail
          url="https://${{ inputs.SCHED_FUNC }}.azurewebsites.net/api/healthz"
          echo "🔍 Probing $url …"

          for attempt in {1..10}; do
            http_code=$(curl -s -o /tmp/healthz.json -w '%{http_code}' "$url" || true)
            printf "Attempt %d → HTTP %s\n" "$attempt" "$http_code"
            if [ "$http_code" = "200" ]; then
              echo "✅ Health check passed:"
              cat /tmp/healthz.json || true
              exit 0
            fi
            echo "⌛ Not ready yet – waiting 15 s"
            sleep 15
          done

          echo "💥 Scheduler health check failed after 10 attempts"
          exit 1

      - name: Grant Cosmos role (scheduler MSI)
        run: |
          set -eo pipefail
          principalId=$(az webapp identity show -g ${{ inputs.RG }} -n ${{ inputs.SCHED_FUNC }} --query principalId -o tsv)
          roleId=$(az cosmosdb sql role definition list -g ${{ inputs.RG }} --account-name ${{ inputs.COSMOS }} \
                   --query "[?roleName=='Cosmos DB Built-in Data Contributor'].id" -o tsv)
          az cosmosdb sql role assignment create -g ${{ inputs.RG }} --account-name ${{ inputs.COSMOS }} \
            --principal-id $principalId \
            --role-definition-id $roleId \
            --scope "/" || true
          echo "✅ scheduler MSI granted data-plane role"

      - name: Update web-app with scheduler settings
        run: |
          set -eo pipefail
          sched_base="https://${{ inputs.SCHED_FUNC }}.azurewebsites.net"

          az webapp config appsettings set \
            -g ${{ inputs.RG }} -n ${{ inputs.APP }} --settings \
            SCHEDULER_BASE_URL=$sched_base \
            SCHEDULER_FUNCTION_NAME=${{ inputs.SCHED_FUNC }} \
            SCHEDULER_MGMT_KEY=""

          echo "🔗 web-app now knows scheduler base $sched_base (no key needed)"

      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: scheduler-log
          path: sched.log
